### PR TITLE
Update proxyConfig.html

### PR DESCRIPTION
**Pull request by GarethFlandro**
Improved readability without editing actual code

### CODE REVIEW

**Review by crllect — CHANGES_REQUESTED** [review]
Something about prettier configs

**Comment by GarethFlandro** [comment]
I don't like your prettier config

**Comment by crllect** [comment]
Well it's my code 😭

**Comment by GarethFlandro** [comment]
Dang it he's good

**Comment by crllect** [comment]
Lmfao

**Pull request closed without merging**
